#ifndef TOKENS_H
#define TOKENS_H
#endif

#define BASE 2
#define REGISTRO 3
#define FIN 4
#define INICIO 5
#define ID 6
#define SALTO 7
#define ENTONCES 8
#define SI 9
#define HACER 10
#define MIENTRAS_QUE 11
#define ESCRIBIR 13
#define LEER 14
#define DEVOLVER 15
#define NO 18
#define MAYOR_QUE 19
#define PARENTESIS_ABRE 22
#define PARENTESIS_CIERRA 23
#define CORCHETE_ABRE 24
#define CORCHETE_CIERRA 25
#define PUNTO 26
#define COMA 27
#define FUNC 28
#define SIN 29
#define MENOR_QUE 30
#define IGUAL 31
#define NUM 32
#define CADENA 33
#define ASIGNACION 34
#define MAS 35
#define MENOS 36
#define MUL 37
#define DIV 38
#define MODULO 39
#define CARACTER 40
#define OO 41
#define YY 42
#define FALSO 43
#define VERDADERO 44
#define MENOS_MENOS 45
#define COMENTARIO_ABRE 46
#define COMENTARIO_CIERRA 47
#define ENT 48
#define REAL 49
#define DREAL 50
#define CAR 51
#define SINO 53
#define MIENTRAS 54